FROM node:7.9.0

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list && \
  apt-get update && \
  apt-get install --no-install-recommends -y google-chrome-stable
